---@meta

---@class ABP_Light_Base_C : AInteractableObject
---@field UberGraphFrame FPointerToUberGraphFrame
---@field LightBulb ULightBulbComponent
---@field SignalReceiverFlickerDestroy USignalReceiverComponent
---@field SignalReceiverFlickerOff USignalReceiverComponent
---@field SignalReceiverFlickerOn USignalReceiverComponent
---@field PhysicsInteraction UPhysicsInteractionComponent
---@field SingleClick USingleClickComponent
---@field SignalReceiverOff USignalReceiverComponent
---@field DamageInteractable UDamageInteractableComponent
---@field Hittable UHittableComponent
---@field SignalReceiverOn USignalReceiverComponent
---@field FlickerPattern_LightIntencityMultiplyer_01_2DB9D6514C154342AF39149971F164DA float
---@field FlickerPattern__Direction_2DB9D6514C154342AF39149971F164DA ETimelineDirection::Type
---@field FlickerPattern UTimelineComponent
---@field SwitchOnClick boolean
---@field PhysicsActivateAfterDestroy boolean
---@field DestractionNiagaraEmitter_OnGlass UNiagaraSystem
---@field SM_DestractibleGlass TArray<UStaticMeshComponent>
---@field SM_UdestractibleSM TArray<UStaticMeshComponent>
---@field PointLights TArray<UPointLightComponent>
---@field InnerPointLights TArray<UPointLightComponent>
---@field OuterPointLights TArray<UPointLightComponent>
---@field SpotLights TArray<USpotLightComponent>
---@field InnerSpotLights TArray<USpotLightComponent>
---@field OuterSpotLights TArray<USpotLightComponent>
---@field ChildActors TArray<ABP_Light_Base_C>
---@field BaseIntensity float
---@field DestractionNiagaraEmitter_OnActor UNiagaraSystem
---@field OnSound UAkAudioEvent
---@field OffSound UAkAudioEvent
---@field FlickSound UAkAudioEvent
---@field DestroySound UAkAudioEvent
---@field FlickerLightIntencityMultiplyerCurve UCurveFloat
---@field FlickerSoundEventsCurve UCurveFloat
---@field NiagaraComponents TArray<UNiagaraComponent>
---@field MaxRandomFlickDelay double
---@field BaseInnerIntensity float
---@field BaseOuterIntensity float
---@field InsectNiagaraComponents TArray<UNiagaraComponent>
---@field UseInsects boolean
---@field ControlledLightsActors TArray<AActor>
---@field NeedOffFlickerOnEndEmission boolean
---@field ['AutoOn/OffMaxDelay'] double
---@field SM_EmissiveGlassOpaque TArray<UStaticMeshComponent>
---@field SM_CustomDepth TArray<UStaticMeshComponent>
---@field SM_EmissiveGlow TArray<UStaticMeshComponent>
---@field bEmissionFlickering boolean
---@field HasBeganPlay boolean
---@field LightFunction_Flickering UMaterialInterface
---@field bIsAffectedByEmission boolean
---@field MultiplyForAmbientLight TArray<double>
---@field IndexMultiplyForAmbientLight int32
---@field TurnOnOffIntensityWhileFlickering double
---@field ParalaxGlass boolean
---@field RaralaxMaterial UMaterialInstance
local ABP_Light_Base_C = {}

function ABP_Light_Base_C:TurnOnControlledLightsActors() end
function ABP_Light_Base_C:TurnOffControlledLightsActors() end
function ABP_Light_Base_C:SetMultiplyArrey() end
---@param Array TArray<ULightComponent>
---@param Value double
---@param Has_Value boolean
function ABP_Light_Base_C:GetIntensityFromLights(Array, Value, Has_Value) end
function ABP_Light_Base_C:CreateDynamicMaterialInstance() end
function ABP_Light_Base_C:SetMaterialEnableFalse() end
function ABP_Light_Base_C:SetMaterialEnableTrue() end
function ABP_Light_Base_C:SetCollisionProfile() end
function ABP_Light_Base_C:PlayDestroySound() end
function ABP_Light_Base_C:PlayFlickeringSound() end
function ABP_Light_Base_C:PlayOnSound() end
function ABP_Light_Base_C:PlayOffSound() end
---@param Sound UAkAudioEvent
function ABP_Light_Base_C:PlaySound(Sound) end
---@param FlickerLightIntencityMultiplyerCurve UCurveFloat
---@param FlickerSoundEventsCurve UCurveFloat
function ABP_Light_Base_C:SetNewFlickPattern(FlickerLightIntencityMultiplyerCurve, FlickerSoundEventsCurve) end
function ABP_Light_Base_C:UserConstructionScript() end
function ABP_Light_Base_C:FlickerPattern__FinishedFunc() end
function ABP_Light_Base_C:FlickerPattern__UpdateFunc() end
function ABP_Light_Base_C:FlickerPattern__SoundEvents_01__EventFunc() end
function ABP_Light_Base_C:ReceiveBeginPlay() end
---@param DataObject UObject
function ABP_Light_Base_C:BndEvt__BP_LightBulb_Base_SignalReceiver_K2Node_ComponentBoundEvent_0_SignalReceiverComponentReceiveSignature__DelegateSignature(DataObject) end
function ABP_Light_Base_C:LightOn() end
function ABP_Light_Base_C:LightOff() end
---@param SpawnEffect boolean
function ABP_Light_Base_C:DestroyLamp(SpawnEffect) end
---@param DataObject UObject
function ABP_Light_Base_C:BndEvt__BP_LightBulb_Base_SignalReceiverOff_K2Node_ComponentBoundEvent_1_SignalReceiverComponentReceiveSignature__DelegateSignature(DataObject) end
function ABP_Light_Base_C:StartFlicker() end
function ABP_Light_Base_C:StopFlicker() end
function ABP_Light_Base_C:BndEvt__BP_Light_Base_SingleClick_K2Node_ComponentBoundEvent_2_InteractSignature__DelegateSignature() end
---@param DataObject UObject
function ABP_Light_Base_C:BndEvt__BP_Light_Base_SignalReceiverFlickerOn_K2Node_ComponentBoundEvent_3_SignalReceiverComponentReceiveSignature__DelegateSignature(DataObject) end
---@param DataObject UObject
function ABP_Light_Base_C:BndEvt__BP_Light_Base_SignalReceiverFlickerOff_K2Node_ComponentBoundEvent_4_SignalReceiverComponentReceiveSignature__DelegateSignature(DataObject) end
---@param DataObject UObject
function ABP_Light_Base_C:BndEvt__BP_Light_Base_SignalReceiverFlickerDestroy_K2Node_ComponentBoundEvent_5_SignalReceiverComponentReceiveSignature__DelegateSignature(DataObject) end
function ABP_Light_Base_C:OnConstruction() end
function ABP_Light_Base_C:SpawnInsects() end
function ABP_Light_Base_C:RemoveInsects() end
function ABP_Light_Base_C:ResetLightsIntencity() end
function ABP_Light_Base_C:OnEmissionStart() end
function ABP_Light_Base_C:OnEmissionFinish() end
function ABP_Light_Base_C:OnDayStart() end
function ABP_Light_Base_C:OnNightStart() end
function ABP_Light_Base_C:FlickOnEmissionStart() end
function ABP_Light_Base_C:FlickOffEmissionEnd() end
function ABP_Light_Base_C:LightOnNightStart() end
function ABP_Light_Base_C:LightOffDayStart() end
---@param OnOff boolean
function ABP_Light_Base_C:GlassEmissive(OnOff) end
---@param LightIntensity double
function ABP_Light_Base_C:GlassEmissiveFlick(LightIntensity) end
---@param LastDamageDealerUID FUID
---@param bProjectileFlownThroughObject boolean
function ABP_Light_Base_C:BndEvt__BP_Light_Base_DamageInteractable_K2Node_ComponentBoundEvent_6_OnDamageAccumulated__DelegateSignature(LastDamageDealerUID, bProjectileFlownThroughObject) end
---@param EntryPoint int32
function ABP_Light_Base_C:ExecuteUbergraph_BP_Light_Base(EntryPoint) end


